hoteladmin/urls.py
from django.urls import path
from . import views
app_name="hoteladmin"
urlpatterns = [
    path("/",views.index,name="index"),
    path("/login",views.view_login,name="login"),
    path("/register",views.register,name='register'),
    path("/orders",views.view_orders,name='orders'),
    path("/orders/<str:order_no>",views.expand_order,name='expandorder')
]

wad/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user',include("user.urls")),
    path('hoteladmin',include("hoteladmin.urls"))
    
]

hoteladmin/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.core.validators import int_list_validator

# Create your models here.
class address(models.Model):
    street=models.CharField (max_length=50)
    city=models.CharField( max_length=50)
    pincode=models.IntegerField()

    def __str__(self):
        return f" {self.street} \n{self.city} \n{self.pincode} "

class Dish(models.Model):
    NORTH_INDIAN='NIN'
    ITALIAN='IT'
    CHINESE='CHI'
    SOUTH_INDIAN='SIN'
    KOREAN='KR'
    SIDE='SD'
    DESSERT='DES'
    BURGER='BUR'
    BEVERAGES='BEV'
    DEFAULT='DEF'
    SOUP='SOU'
    SALAD='SAL'
    CATEGORY=[(NORTH_INDIAN,'North Indian'),(ITALIAN,"Italian"),(CHINESE,'Chinese'),
    (SOUTH_INDIAN,'South Indian'),(KOREAN,'Korean'),(SIDE,'Side'),(DESSERT,'Dessert'),
    (BURGER,'Burger'),(BEVERAGES,'Beverages'),(SOUP,'Soup'),(SALAD,"Salad")]
    TIME=[('BR','BreakFast'),('LN','Lunch'),('DI','Dinner')]
    veg=models.BooleanField(default=False)
    name=models.CharField( max_length=50)
    image=models.ImageField(upload_to='images/',blank=True)
    avail=models.BooleanField(default=True)
    served_at=models.CharField(max_length=2,choices=TIME,blank=True)
    
    avg_time=models.IntegerField(default=15)
    price=models.IntegerField(default=0)
    category=models.CharField( max_length=4,choices=CATEGORY,default=DEFAULT)

    
    def __str__(self):
        return f"{self.name} - {self.price}"


#Order items-Erases after timeout interval
class Item(models.Model):
    dish=models.ForeignKey(Dish,on_delete=models.CASCADE,related_name='+')
    quantity=models.IntegerField(default=1)
    
    def get_price(self):
        return int(self.dish.price*self.quantity)
class Order(models.Model):
    PENDING='PD'
    CONFIRM='CON'
    PAID='PD'
    ORDER_STATUS=[(PENDING,'Pending'),(CONFIRM,'Confirm')]
    BILL_STATUS=[(PENDING,'Pending'),(PAID,'Paid')]
    order_no=models.CharField(max_length=10,primary_key=True)
    items=models.ManyToManyField(Item,related_name='+')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='orders')
    order_status=models.CharField(max_length=3,choices=ORDER_STATUS,default=PENDING)
    bill_status=models.CharField(max_length=3,choices=BILL_STATUS,default=PENDING)
    restaurant=models.ForeignKey('Restaurant',related_name='+',on_delete=models.CASCADE,null=True)
    date=models.DateField(blank=True,null=True)
    time=models.TimeField(blank=True,null=True)
    avg_time=models.IntegerField(default=0)
    table_no=models.IntegerField(default=0)
    price=models.IntegerField(default=0)

    def __str__(self):
        return f"{self.order_no}  "



class Restaurant(models.Model):
    avail_payment=[('UPI','UPI PhonePe'),('CASH','Cash Only')]
    MULTI='MC'
    Cuisine=[(MULTI,'MultiCuisine Restaurant'),('VEG','Pure Veg')]
    OPEN='OP'
    CLOSED='CL'
    STATUS=[(OPEN,'Open'),(CLOSED,'Closed')]
    
    name=models.CharField( max_length=50)
    address=models.ForeignKey( address, on_delete=models.CASCADE,related_name="restaraunt")
    dishes=models.ManyToManyField(Dish,blank=True,related_name='restaraunt')
    capacity=models.IntegerField(default=20)
    seating_capacity=models.IntegerField(default=50)
    buffer=models.IntegerField(default=0,null=True)
    
    takeaway=models.BooleanField(blank=True,default=False)
    payment=models.CharField(max_length=4,choices=avail_payment,default='Cash')
    orders=models.ManyToManyField(Order,blank=True,related_name='+')
    combos=models.ManyToManyField(Dish,blank=True,related_name='+')
    open_time=models.TimeField(blank=True,null=True)
    date=models.DateField(null=True,default=date.today)
    close_time=models.TimeField(blank=True,null=True)
    cuisine=models.CharField(max_length=4,choices=Cuisine,default=MULTI)
    status=models.CharField(max_length=3,choices=STATUS,default=OPEN)
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name='restaurant',null=True)
    rest_id=models.CharField(max_length=10,default='DEF001')
    
    class Meta:
        constraints=[
            models.UniqueConstraint(fields=['rest_id'],name='rest_id_constraint')
        ]
    def __str__(self):
        return f"{self.name} {self.cuisine} Restaraunt-{self.rest_id}"


class Reservations(models.Model):
    PENDING='PD'
    CONFIRM='CON'
    STATUS=[(PENDING,'Pending'),(CONFIRM,'Confirm')]
    conf_code=models.CharField(max_length=30)
    user=models.ForeignKey(User,null=True,on_delete=models.CASCADE,related_name='reservations')
    cust_name=models.CharField(max_length =25)
    date=models.DateField(null=True)
    status=models.CharField(max_length=4,choices=STATUS,default=PENDING)
    tables=models.IntegerField(null=True)
    time=models.TimeField(null=True)
    restaurant=models.ForeignKey(Restaurant,null=True,blank=True,related_name='reservations',on_delete=models.CASCADE)
    TimeOut=models.TimeField(null=True)
    table_no=models.CharField(validators=[int_list_validator],max_length=200,default='',null=True)

    

    def __str__(self):
        return f"{self.conf_code} {self.cust_name}"
class Global(models.Model):
    order_no=models.IntegerField(default=1)
    cnf_no=models.IntegerField(default=1)
    rest_no=models.IntegerField(default=1)

hoteladmin/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User,Group
from django.contrib.auth import login,logout,authenticate
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import *
from .functions import *
from datetime import date
# Create your views here.

def index(request):
    if request.user.is_authenticated:
        return render(request,"hoteladmin/index.html",{
            "user":request.user.username.capitalize() } )
    else:
        return HttpResponseRedirect(reverse('hoteladmin:login'))
    
def view_login(request):
    if(request.method=="POST"):
        errormessage="Incorrect crendetials or the account doesnt exist"
        passmismatch="Passwords don't match.Please enter again."
        Permdenied="Permission Denied"
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(request,username=username,password=password)
        if user is not None:
            if user.groups.filter(name='HotelAdmin').exists():
                login(request,user)
                #Redirect to index view 
                return HttpResponseRedirect(reverse('hoteladmin:index'))
            else:
                return render(request,"hoteladmin/login.html",{
                    "message":Permdenied
                })
        else:
           return  render(request,"hoteladmin/login.html",{
               "message":errormessage
           })
    return render(request,"hoteladmin/login.html")

    

def register(request):
    if request.method=="POST":
        usernameexists="Username already exists.Choose a new username"
        userexists="Account already exists.Please sign in to continue"
        passerror="The passwords don't match.Please enter again"
        resexists="The  Restaurant  already exists"
        reserror="Cant Register Restaurant"
        addresserr="Can't Add Address Try Again"
        resname=request.POST['resname']
        street=request.POST['street']
        city=request.POST['city']
        pincode=request.POST['pincode']
        email=request.POST['email']
        seating_capacity=request.POST['seating_capacity']
        date=request.POST['date']
        open_time=request.POST['opening_time']
        close_time=request.POST['closing_time']
        cuisine=request.POST['cuisine']
        payment=request.POST['payment']
        takeaway=request.POST['takeaway']
        username=request.POST['user_name']
        password=request.POST['password']
        password1=request.POST['password1']
        addr=address.objects.create(street=street,city=city,pincode=pincode)
        no=get_number(Global)
        rest_id="DEF"+str(no)
        
        if addr is  None:
            return render(request,"hoteladmin/register.html",{
                "message":addresserr
            })
        if password!=password1:
            return render(request,"hoteladmin/register.html",{
                "message":passerror
            })
        allusers=User.objects.all()
        for user in allusers:
            if(user.username==username):
                if(user.email==email):
                    return render(request,"hoteladmin/register.html",{
                        "message":userexists
                    })
                
                return render(request,"hoteladmin/register.html",{
                    "message":usernameexists
                })
        user=User.objects.create_user(username=username,password=password,email=email)
       
        if user is not None:
            restaurant=Restaurant.objects.create(name=resname,address=addr,seating_capacity=seating_capacity,takeaway=takeaway,payment=payment,user=user,open_time=open_time,close_time=close_time,cuisine=cuisine,rest_id=rest_id)
            if restaurant is None:
                resall=Restaurant.objects.all()
                if restaurant in resall:
                    return render(request,"hoteladmin/register.html",{
                        "message":resexists
                    })
                else:
                    return render(request,"hoteladmin/register.html",{
                        "message":reserror
                    }) 
            else:
                group=Group.objects.get(name='HotelAdmin')
                group.user_set.add(user)
                group.save()
                return HttpResponseRedirect(reverse('hoteladmin:login'))
        else:
            return render(request,"hoteladmin/register.html",{
                        "message":"User Cant be created"
                    }) 
           
    return render(request,"hoteladmin/register.html")

def view_orders(request):
    user=request.user
    restaurant=user.restaurant
    orders=restaurant.orders.all()
    
    return render(request,"hoteladmin/orders.html",{
        "orders":orders,
    })
def expand_order(request,order_no):
    order=Order.objects.get(order_no=order_no)
    return render(request,"hoteladmin/expandorder.html",{
        "order":order
    })

hoteladmin/templates/hoteladmin/index.html
{% load static %}
<!DOCTYPE html>


<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>AdminIndex</title>
  <link rel="icon" type="image/png" href="{% static 'hoteladmin/tablologo.png'%}">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'hoteladmin/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  
</head>

<body>
  

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">tablO</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Download QR code
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Edit profile details</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
      <h1 class="display-3">Welcome {{user}}</h1>
      <p class="lead">We are so glad of your association with us</p>
      <a href="#" class="btn btn-primary btn-lg">Profile</a>
    </header>

    <!-- Page Features -->
    <div class="row text-center">

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src= "{% static 'hoteladmin/foodmenu.jpg' %}" width="300" height="300" alt="">
          <div class="card-body">
            <h4 class="card-title">Edit Menu</h4>
            <p class="card-text">Update your menu here regularly</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Click here</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="{% static 'hoteladmin/orders.png' %}" width="300" height="300" alt="">
          <div class="card-body">
            <h4 class="card-title">Orders</h4>
            <p class="card-text">Check table-wise orders and statuses</p>
          </div>
          <div class="card-footer">
            <a href="{% url 'hoteladmin:orders'%}" class="btn btn-primary">Click here</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="{% static '/hoteladmin/reserv.jpg' %}" width="300" height="300" alt="">
          <div class="card-body">
            <h4 class="card-title">Reservations</h4>
            <p class="card-text">View and update reservation info</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Click here</a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-md-6 mb-4">
        <div class="card h-100">
          <img class="card-img-top" src="{% static '/hoteladmin/feed.jpg' %}" width="300" height="300" alt="">
          <div class="card-body">
            <h4 class="card-title">Feedback</h4>
            <p class="card-text">Check out the feedback given by your customers</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Click here</a>
          </div>
        </div>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white"></p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{%static '/hoteladmin/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{%static '/hoteladmin/bootstrap.bundle.min.js' %}" type="text/javascript" ></script>

</body>

</html>