user/urls.py
from django.urls import path
from . import views
app_name='user'
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path("/",views.index,name="index"),
    path("/login",views.view_login,name="login"),
    path("/signup",views.signup,name="signup"),
    path("/contact",views.contact,name="contact"),
    path("/test",views.test,name="test"),
    path("/restaurant/<str:rest_id>",views.view_restaurant,name='view_restaurant'),
    path("/booking/",views.booking,name='booking'),
    path("/booking/confirmreservation",views.confirm_res,name='confirmres'),
    path("/qrcode",views.qrcode,name='qrcode'),
    path("/logout",views.logout_view,name='logout'),
   
    path('cart',views.cart,name='cart'),
    path('/orderconf',views.order_conf,name='orderconf'),
    path('/ordersuccess',views.place_order,name='ordersuccess'),
    path('ajax/validate_username',views.validate_username,name='validate_username')

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

wad/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user',include("user.urls")),
    path('hoteladmin',include("hoteladmin.urls"))
    
]

user/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate,logout
from django.http  import HttpResponseRedirect,HttpResponse,JsonResponse
from django.urls import reverse
# Create your views here.
from hoteladmin.models import *
from .decorators import *
from django.contrib.auth.decorators import login_required
from datetime import date,time
from datetime import datetime
from wad.settings import BASE_DIR


def index(request):
    request.session.set_expiry(0)
    if request.user.is_authenticated:
        username=request.user.username.capitalize()
        return render(request,"user/index.html",{
            "username":username
        })
    else: #Ask the user to login
        return HttpResponseRedirect(reverse('user:login'))

def signup(request):
    if(request.method=="POST"):
        #Error messages
        usernameexists="Username already exists.Choose a new username"
        userexists="Account already exists.Please sign in to continue"
        passerror="The passwords don't match.Please enter again"
        #POST data
        username=request.POST['username']
        password=request.POST.get('password')
        passverify=request.POST.get('password1')
        email=request.POST.get('email')

        #Checking whether the entered two passwords match
        if password != passverify:
            return render(request,"user/signup.html",{
                "message":passerror
            })
        
        #Checking if the username or the user already exists
        allusers=User.objects.all()
        for user in allusers:
            if(user.username==username):
                if(user.email==email):
                    return render(request,"user/signup.html",{
                        "message":userexists
                    })
                
                return render(request,"user/signup.html",{
                    "message":usernameexists
                })
        user=User.objects.create_user(username=username,password=password,email=email)
        user.save()
        userauth=authenticate(username=username,password=password)
        if userauth:
            #Redirect to login view
            return HttpResponseRedirect(reverse('user:login'))
        else:
            return HttpResponse(request,"Cant create user")
    return render(request,"user/signup.html")
def view_login(request):
    if(request.method=="POST"):
        errormessage="Incorrect crendetials or the account doesnt exist"
        passmismatch="Passwords don't match.Please enter again."
        username=request.POST['username']
        password=request.POST['password']
       
        user=authenticate(request,username=username,password=password)
        if user is not None:    
            login(request,user)
            #Redirect to index view
            
            return HttpResponseRedirect(reverse('user:index',))

        else:
           return  render(request,"user/login.html",{
               "message":errormessage
           })
    return render(request,"user/login.html")
def contact(request):
    return render(request,"user/contact.html")

def booking(request,):
    if request.method=="POST":
        request.session['rests']=request.POST['rest']
        rest_code=request.session['rests']
        restaurant=Restaurant.objects.get(rest_id=rest_code)
        capacity=tables_avail(restaurant)
        return render(request,"user/booking.html",{
            "no":capacity
        })
    return HttpResponseRedirect(reverse('user:test'))
def test(request):
    return render(request,"user/test.html",{
        "restaurants":Restaurant.objects.all()
    })
def confirm_res(request):
    if request.method=="POST":
        tables=request.POST['no'] #No of the tables
        name=request.POST['name'] #Name of the customer
        date=request.POST['date'] #date of reservation
        time=request.POST['time'] #Time
        rest_code=request.session['rests']
        restaurant=Restaurant.objects.get(rest_id=rest_code)
        glob=Global.objects.get(pk=1)
        cnf_code='CNF'+str(glob.cnf_no)
       
        rest_id=request.session['rests']
        reservation=Reservations.objects.create(conf_code=cnf_code,user=request.user,cust_name=name,date=date,
        tables=tables,time=time,restaurant=restaurant)
        if reservation is not None:
            glob.cnf_no +=1
            glob.save()
            set_tableno(reservation)
            reservation.save()
            return render(request,"user/resconfirm.html",{
                "reservation":reservation
            })
        else:
            return HttpResponse('Reservation cant be made ')
    
    return HttpResponseRedirect(reverse('user:test'))   
    
@login_required(redirect_field_name='/usertest1',login_url='/user/login')
def view_restaurant(request,rest_id):
    if request.method=="POST":
        orderdata=request.POST['orderdata']
        request.session['cart']=decode(orderdata) #First time the user orders
        return HttpResponseRedirect(reverse('user:orderconf'))
    restaurant=Restaurant.objects.get(rest_id=rest_id)
    request.session['rest']=rest_id
    return render(request,"user/menu.html",{
        "restaurant":restaurant,"dishes":restaurant.dishes.all()
    })
def qrcode(request):
    data=readqr()
    return HttpResponseRedirect(data)
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('user:login'))
#Order Confirmation page
def order_conf(request):
    orderdata=request.session['cart']
    items={}
    price=get_price(orderdata)
    for key in orderdata.keys():
        dish=Dish.objects.get(pk=key)
        quantity=orderdata[key]
        items[dish]=quantity
    return render(request,"user/orderconf.html",{
        "dishes":items,"price":price,
    })
        


def cart(request):
    orderdata=request.session['cart']
    items=[]
    for key in orderdata.keys():
        dish=Dish.objects.get(pk=key)
        quantity=orderdata[key]
        items.append(dish.name+ str(quantity)+ 'X'+ '-' +str(dish.price*quantity) )
    return render(request,"user/cart.html",{
        "items":items
    })
def place_order(request):
    if request.method=="POST":
        if(order_exists(request.user)):
            pass
        else:
            pass
#Testing Ajax
def validate_username(request):
    username=request.GET['username']
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)

    

 

user/templates/user/booking.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">

    <title>Reserve your table</title>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" crossorigin="anonymous">
    


</head>


<body>
    <div class="jumbotron ">
        <div class="container text-center bookTable ">
            <h1 class="upper-case">Book Your Table</h1>
            <h2>Tables Available : {{no}}</h2>
            <h2 id='msg' style="color: red;"></h2>



        </div>
    </div>





    <form action="{% url 'user:confirmres' %}" class="form-horizontal customerForm" method="post">
        {% csrf_token %}
        <div class="form-group col-md-6 col-lg-6 col-sm-12">
            <label for="user-name" class="col-lg-2 control-label">Name</label>
            <div class="col-lg-10">
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-user"></span>
                    <input type="text" class="form-control" name="name" id="user-name" placeholder="Enter you name" required>

                </div>

            </div>
        </div>
        <!-- End form group -->


        <div class="form-group col-md-6 col-lg-6 col-sm-12">
            <label for="phone" class="col-lg-2 control-label">Contact</label>
            <div class="col-lg-10">
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-earphone"></span>
                    <input type="tel" class="form-control" name="phoneno" id="phone" placeholder="Phone Number" required>

                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-3 col-md-3"></div>
            <div class="form-group  col-md-6 col-lg-6 col-sm-12">
                <label for="party" class="col-lg-2 control-label">No of tables</label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <span class="input-group-addon glyphicon glyphicon-hand-right"></span>
                        <input type="tel" class="form-control" name="no" id="tables" placeholder="Enter No of tables" required>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3"></div>
        </div>





        <div class="form-group col-md-6 col-lg-6 col-sm-12">
            <label for="date" class="col-lg-2 control-label">Date</label>
            <div class="col-lg-10">
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-hand-right"></span>

                    <input type="date" class="form-control" id="date" name="date" placeholder="Choose a Date" required>
                </div>
            </div>
        </div>

        <div class="form-group col-md-6 col-lg-6 col-sm-12">
            <label for="time" class="col-lg-2 control-label">Time</label>
            <div class="col-lg-10">

                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-hand-right"></span>
                    <input type="time" class="form-control" id="time" name="time" placeholder="Choose a Time" required>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-3 col-md-3"></div>
            <div class="form-group  col-md-6 col-lg-6 col-sm-12">
                <label for="user-message" class="col-lg-2 control-label">Message</label>
                <div class="col-lg-10">
                    <textarea name="user-message" id="user-message" name="message" class="form-control" cols="5" rows="10" placeholder="Enter your Special needs"></textarea>
                </div>
            </div>
            <div class="col-lg-3 col-md-3"></div>
        </div>

        <input id="capacity" type="hidden" value="{{no}}">


        <div class=" col-lg-12 form-group text-center">
            
            <input  id="submit" type="submit" value="Submit">
            
            <!--Modal to display the confirmation code-->

            <!--<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">-->
            <!--<div class="modal-dialog modal-sm">-->
            <!--<div class="modal-content" id="op"  >-->
            <!--...-->
            <!--</div>-->
            <!--</div>-->
            <!--</div>-->



            <!--<button type="button" id="edit" class="btn btn-warning" data-toggle="tooltip" data-placement="right" title="Tooltip on right" data-content="Click to edit an existing reservation">Edit</button>-->

        </div>
        <hr>

    </form>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script>
    var capacity= document.getElementById('capacity').value
    $("#tables").change(
        function(){
            var tables= $(this).val()
            console.log(tables)
            if(Number(tables) > Number(capacity)){
            document.getElementById('msg').innerHTML='Not enough tables are present to complete the reservation'
            document.getElementById('submit').disabled=true;
        }
        else{
            document.getElementById('msg').innerHTML=''
            document.getElementById('submit').disabled=false;
        }
    }
)
</script>
</body>

</html>

user/templates/user/contact.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contact</title>
    <link href="{% static 'user/contact.css' %}" type="text/css" rel="stylesheet" />
</head>

<body>
    <div class="cntfrm">
        <h1 id="hcn">Contact Us</h1>
        <p id="gr">Tablo beleive in good relationship with customer , so if you need any help feel free to contact us .</p>
        <div class="cnbox">
            <form>
                <input type="text" id="name" name="Name" placeholder="Name...">
                <input type="text" id="email" name="Email Id" placeholder="Email Id..">
                <textarea type="text" id="message" name="Message" placeholder="Message.."></textarea>
                <input type="submit" id="clk" value="Send Message">
            </form>
        </div>
    </div>
</body>

</html>

user/templates/user/index.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'user/index.css' %}" type="text/css" rel="stylesheet" />

</head>

<body>
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a class="o1" href="{% url 'user:login' %}">Login</a>
        <a class="o2" href="{% url 'user:signup' %}">Signup</a>
        <a class="o3" href="{% url 'user:contact' %}">Contact Us</a>
        <a class="o4" href="{% url 'user:signup'%}"><img id="scamg" src="https://img.icons8.com/ios/2x/qr-code--v2.gif" alt=""></a>
        <img src="https://media.istockphoto.com/vectors/people-set-profession-waiter-vector-id954891426?k=6&m=954891426&s=612x612&w=0&h=WpjbuIUXPGQsZCC2-tGpf0r1ZgNhZTJdCi3Ot1T-p6c=" alt="" id="navimg">
    </div>

    <div class="row1" id="main">
        <span id="sp1" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
        <div class="cola one">
            <div class="box1" id="main1">
                <img id="img1" src="https://media3.giphy.com/media/l1NbTlEHomLoTEoZBP/giphy.gif">
            </div>
        </div>
        <div class="cola two">
            <div class="box2">
                <div class="options" id="opt">
                         {% if username %}
                         <a class="o1" href="">Welcome Back {{username}}</a>
                        {%endif%}
                        {% if not username%}
                    <a class="o1" href="{% url 'user:login' %}">Login</a>
                    <a class="o2" href="{% url 'user:signup' %}">Signup</a>
                        {%endif%}
                    <a class="o3" href="{% url 'user:test'%}">Reserve a Table</a>
                    <a class="o4" href="{% url 'user:qrcode'%}"><img id="scamg" src="https://img.icons8.com/ios/2x/qr-code--v2.gif" alt=""></a>
                    <a class="o5" href="{% url 'user:logout' %}">Log Out</a>
                    <a class="o5" href="">My Orders</a>
                    <a class="o5" href="">Reservations</a>
                </div>

                <img id="logo" src="{% static 'user/tablologo.png' %}">
                <h1 id="mainheading">TablO</h1>
                <input type="text" id="search" onkeyup="" placeholder="Search.." title="Type in a category">
            </div>
        </div>
    </div>

    <div class="stepbox">
        <div class="stepsa">
            <img class="b1 scan" src="https://media1.giphy.com/media/KjWDaVqI6waTtJmEXT/giphy.webp?cid=ecf05e47i401b8q0fz8rt4brgop90rx50sm3oni5tg19h0xb&rid=giphy.webp" alt="">
            <h1 class="b1 step1">Scan QR CODE</h1>
        </div>
        <div class="stepsb">
            <h1 class="b3 step2">ORDER</h1>
            <img class="b3 scan2" src="https://media4.giphy.com/media/26BRJtpO9vE6LJCWk/200w.webp?cid=ecf05e47wth8zbzqqk2y9h27tmy670m5xzmm4fd0hifv4y5y&rid=200w.webp" alt="">
        </div>
    </div>
    <div class="info">

        <div class="info1 inftxt1"><img id="infimg" src="https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375__340.png" alt=""></div>
        <div class="info1 inftxt2">
            <p>Don't waste food .</p>
            <p>Take as much you can eat .</p>
        </div>

    </div>
    <div class="rowp">
        <div class="colp colq">
            <img class="dish1" src="https://images.unsplash.com/photo-1596450512748-2dae774fc38a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTl8fGluZGlhbiUyMGZvb2R8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" " alt=" ">
		     <div class="dishname1 ">
				 <a id="flink " href=" "><h1>INDIAN FOOD</h1></a>
			 </div>
		</div>
		<div class="colp colr ">
			<img class="dish1 "  src="https://images.unsplash.com/photo-1512152272829-e3139592d56f?ixid=MXwxMjA3fDB8MHxzZWFyY2h8M3x8ZmFzdCUyMGZvb2R8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 ">
            <div class="dishname1 ">
				<a id="flink " href=" "><h1>BURGER</h1></a>
			</div>
		</div>
		<div class="colp cols ">
            <img class="dish1 " src="https://images.unsplash.com/photo-1513104890138-7c749659a591?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8cGl6emF8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 ">
			<div class="dishname1 ">
				<a id="flink " href=" "><h1>PIZZA</h1></a>
			</div>
		</div>
	</div>
	<div class="rowp ">
		<div class="colp colq ">
			<img class="dish1 " src="https://images.unsplash.com/photo-1504712168631-d59c8516c409?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzV8fGljZWNyZWFtfGVufDB8fDB8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 ">
            <div class="dishname1 ">
				<a id="flink " href=" "><h1>ICE CREAM</h1></a>
			</div>
		</div>
		<div class="colp colr ">
			<img class="dish1 " src="https://images.unsplash.com/photo-1500353391678-d7b57979d6d2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MzJ8fGNvZmZlZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 "> 
         <div class="dishname1 ">
            <a id="flink " href=" "><h1>COFFEE</h1></a>
			</div>
		</div>
		<div class="colp cols ">
			<img class="dish1 " src="https://images.unsplash.com/photo-1518047601542-79f18c655718?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTZ8fGNha2V8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60 " >
            <div class="dishname1 ">
				<a id="flink " href=" "><h1>CAKE</h1></a>
			</div>
		</div> 
	</div>
    <hr>
	<div class="cntfrm ">
        <h1 id="hcn ">Contact Us</h1>
        <p id="gr ">Tablo beleive in good relationship with customer , so if you need any help feel free to contact us .</p>
        <div class="cnbox "id="cnbox ">
            <form>
               <input type="text " id="name " name="Name " placeholder="Name... ">
               <input type="text " id="email " name="Email Id " placeholder="Email Id.. ">
	           <textarea type="text " id="message " name="Message " placeholder="Message.. "></textarea>
               <input type="submit " id="clk " value="Send Message ">
            </form>
          </div>
    </div>
    
    <div class="foot ">
        <div class="f f1 ">
             <h1>About us</h1>
             <p>
                 Tablo is made to serve people . It help people to order food sitting in restaurant without any contact. You need to just scan qr code and select from menu and order .
             </p>
             <p>
                 ENJOY YOUR MEAL 
             </p>
        </div>
        <hr>
        <div class="f f3 ">
            <h1>SOCIAL MEDIA</h1>
            <a href=" "><img id="footimg " src="https://img.icons8.com/fluent/2x/instagram-new.png " alt=" "></a>
            <a href=" "><img id="footimg " src="https://img.icons8.com/fluent/2x/facebook-new.png " alt=" "></a>
            <a href=" "><img id="footimg " src="https://img.icons8.com/color/2x/youtube-play.png " alt=" "></a>
            <a href=" "><img id="footimg " src="https://img.icons8.com/fluent/2x/twitter.png " alt=" "></a>
        </div>
    </div>

    <script>
        function openNav() {
          document.getElementById("mySidenav ").style.width = "250px ";
          document.getElementById("main ").style.marginLeft = "0px ";
          document.body.style.backgroundColor = "rgba(0,0,0,0.4) ";
        }
        
        function closeNav() {
          document.getElementById("mySidenav ").style.width = "0 ";
          document.getElementById("main ").style.marginLeft= "0 ";
          document.body.style.backgroundColor = "white ";
        }
        </script>
</body>
</html>

user/templates/user/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
<title>User Registration Form</Form></title>
<link rel="icon" type="image/png" href="tablologo.png">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	color: #fff;
	background: #63738a;
	font-family: 'Roboto', sans-serif;
}
.form-control {
	height: 40px;
	box-shadow: none;
	color: #969fa4;
}
.form-control:focus {
	border-color: #5cb85c;
}
.form-control, .btn {        
	border-radius: 3px;
}
.signup-form {
	width: 450px;
	margin: 0 auto;
	padding: 30px 0;
  	font-size: 15px;
}
.signup-form h2 {
	color: #636363;
	margin: 0 0 15px;
	position: relative;
	text-align: center;
}
.signup-form h2:before, .signup-form h2:after {
	content: "";
	height: 2px;
	width: 30%;
	background: #d4d4d4;
	position: absolute;
	top: 50%;
	z-index: 2;
}	
.signup-form h2:before {
	left: 0;
}
.signup-form h2:after {
	right: 0;
}
.signup-form .hint-text {
	color: #999;
	margin-bottom: 30px;
	text-align: center;
}
.signup-form form {
	color: #999;
	border-radius: 3px;
	margin-bottom: 15px;
	background: #f2f3f7;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
	padding: 30px;
}
.signup-form .form-group {
	margin-bottom: 20px;
}
.signup-form input[type="checkbox"] {
	margin-top: 3px;
}
.signup-form .btn {        
	font-size: 16px;
	font-weight: bold;		
	min-width: 140px;
	outline: none !important;
}
.signup-form .row div:first-child {
	padding-right: 10px;
}
.signup-form .row div:last-child {
	padding-left: 10px;
}    	
.signup-form a {
	color: #fff;
	text-decoration: underline;
}
.signup-form a:hover {
	text-decoration: none;
}
.signup-form form a {
	color: #5cb85c;
	text-decoration: none;
}	
.signup-form form a:hover {
	text-decoration: underline;

}  
h4{
	color: red;
	text-align: center;
}
</style>
</head>
<body>
<div class="signup-form">
    <form action="{% url 'user:signup'%}" method="post">
        {% csrf_token %}
        <h2>Register</h2>
        {% if message %}
        <h4>{{message}} </h4>
        {%endif%}
		<p class="hint-text">Please Register </p>
		<div class="form-group">
        	<input type="User name" id="username" class="form-control" name="username" placeholder="User name" required="required">
        </div>
        <div class="form-group">
            <input type="email" class="form-control" name="email" placeholder="Email Address" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password" required="required">
        </div>
		<div class="form-group">
            <input type="password" class="form-control" name="password1" placeholder="Confirm Password" required="required">
        </div>          
		<div class="form-group">
            <button type="submit" class="btn btn-success btn-lg btn-block">Register</button>
        </div>
    </form>
	<div class="text-center">Already registered?<a href="{% url 'user:login'%}"> Log In</a></div>
</div>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script>
	$("#username").change(
	function (){
		var username= $(this).val();
		$.ajax({
			url : '{% url "user:validate_username" %}',
			data: {
				"username":username
			},
			dataType: 'json',
			success : function(data){
				if(data.is_taken){
					alert('A user with this username already exists')
				}
			},
			error: function(jqXHR, textStatus, errorThrown) {
                console.log(JSON.stringify(jqXHR));
                console.log("AJAX error: " + textStatus + ' : ' + errorThrown);
            }
		})

	}
)

</script>

</body>
</html>

user/templates/user/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choose Restaurant</title>
</head>
<body>
<form action="{% url 'user:booking' %}" method="post">
    {% csrf_token %}
    <label for="rests" >Choose a Restaurant:</label>
    <select id="rest" name="rest">
        {% for restaurant in restaurants %}
      <option value="{{restaurant.rest_id}}">{{restaurant.name}} {{restaurant.cuisine}} Restaurant-{{restaurant.rest_id}}</option>
      {%empty%}
        <option>No restaurants</option>
      {%endfor%}
    </select>
    <input type="submit" value="submit">
</form>
</body>
</html>